### ISSUE TITLE
few questions

### ISSUE THREAD

**Issue by cirilla** [ericwlange/AndroidJSCore#19]
Hi

Thank you for the library, it is really useful!

When are you planning to fix the 2.1 version?
and are you planning to upload the library to remote repository?

Thanks

**Comment by ericwlange** [comment]
I have been working on 2.2, which would include a fix for the 2.1 bug.  I have not yet fixed the bug, because despite the community telling me there _is_ a bug, nobody has sent me a failure case that I can use to debug.  Failing that, I will solve the problem using a more brute force method.  I do hope to wrap up the next release in the next week.

I will use a remote repository for 2.2.

**Comment by ericwlange** [comment]
Please try the latest [pre-release of 2.2](https://github.com/ericwlange/AndroidJSCore/releases/tag/2.2-pre1).  Let me know if it solves the stability problems.  Once it is fully debugged, I will add to a remote repo.

**Comment by ericwlange** [comment]
Closing as the the hanging bug was fixed in 2.2-pre2 and I have another issue open related to the remote repository.
