### ISSUE TITLE
question : async

### ISSUE THREAD

**Issue by x4080** [ericwlange/AndroidJSCore#23]
is it running in the background? if not can it run in asynctask?

thanks and great job

**Comment by ericwlange** [comment]
The short answer is, no it does not run in the background, but yes, you can run it in `AsyncTask`.

The long answer is that it JS will actually execute in a separate thread, but the calling thread blocks until that thread returns.  The reason for this is (1) the main thread has a shallow stack that can overflow if you run in that thread, and (2) JS is a single-threaded environment by design and calling into the same JSContext from multiple threads is not safe.  The AndroidJSCore implementation (in versions 2.1+) solves these problems by setting up a worker thread and all calls to the environment queue in that single thread.

**Comment by x4080** [comment]
Thanks
