### ISSUE TITLE
Defensive System.loadLibrary usage

### ISSUE THREAD

**Issue by cmc5788** [ericwlange/AndroidJSCore#28]
See https://github.com/square/duktape-android/issues/28 and the solution over at https://github.com/KeepSafe/ReLinker - might be a good idea to get ahead of the curve on known `System.loadLibrary` flakiness on certain devices before this becomes a larger issue:

https://github.com/ericwlange/AndroidJSCore/blob/d6af1b813970e4ff3eeef037be17e80618cd52d4/AndroidJSCore/AndroidJSCore/src/main/java/org/liquidplayer/webkit/javascriptcore/JSContext.java#L352

**Comment by ericwlange** [comment]
This is potentially fantastic.  Thanks for the pointer.  I spent many, many, many weeks with [the `hemroid` project](https://github.com/ericwlange/hemroid) just debugging library loading/dependency issues.  I will play around with this.

**Comment by ericwlange** [comment]
I tried to use this library, but it doesn't work for my purposes.  It requires the application context to work, and since I am a library, I don't have access to that context.  I can ask the user to provide it but that breaks backward compatibility.  I also tried using some hacks to get it, and it worked sometimes but failed others.  So I am going to take my chances with `System.loadLibrary()` until I get reports of issues.
