### ISSUE TITLE
Is there support for reading/saving files?

### ISSUE THREAD

**Issue by mikeyxkcd** [ericwlange/AndroidJSCore#30]
Is there support for using some apis such as `FileReader` or `Uint8Array`, or any way to efficiently process potentially large files?

I'm having trouble figuring out which APIs are browser specific and which ones are available to this library.

**Comment by ericwlange** [comment]
I have actually added support for Typed Arrays (including Uint8Array) in my local repo.  I haven't checked it in yet.  Give me a day to do so.

**Comment by mikeyxkcd** [comment]
Cool, that's good to hear. Any reason why it wasn't included in the first place?

Do you mind telling me how to go about figuring out what APIs are currently available to me via the library e.g file reading?

**Comment by ericwlange** [comment]
`FileReader` will not be available because it is a web API, not part of core JavaScript.  It is a browser implementation.  Typed arrays are part of JavaScript, so they are supported.  You can find the JavaScript built-in objects documented [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects).  The JavaScriptCore library I am using appears to support all of the latest bells and whistles.

Even typed arrays are already supported in the current versions.  The only thing I have added locally (I will check in soon, I swear -- but I am chasing another bug) is a convenient interface to Java.  But you don't need that to make use of it in JavaScript itself.  It's already there.

For example, I am adding the ability to create `UintArray` from Java like so:
```
JSUint8Array arr = new JSUint8Array(context, 100);
arr.fill(0xff);
```

But you can already do it this way:
```
context.evaluateScript("var arr = new Uint8Array(100); arr.fill(0xff);");
JSValue arr = context.property("arr");
```

The reason it wasn't included in the first place is because it is a lot of work.

**Comment by mikeyxkcd** [comment]
Neat, thanks for the link to the docs, you have no idea how long I've been looking for it!

And don't worry too much about the Java interface. That's not strictly required as most of my invocations will be dynamic anyways. I just wanted to know what APIs I had to work with.

Keep up the good work dude!

**Comment by ericwlange** [comment]
Typed array support now added in 3.0-pre2
