### ISSUE TITLE
Call Java functions 10000 times from JS

### ISSUE THREAD

**Issue by LiuHongtao** [ericwlange/AndroidJSCore#39]
Hi, thanks for your work, it helps me a lot.

As the code shows, `func()` is called from JS for 10000 times. It spends about 380ms on Genymotion and about 1200ms on my phone, which seems a little bit long. Did i do something wrong? Does time are spend on java reflection?

Another Problem: If `func()` is called 50000 times or a lager number, the first start of TestActivity is ok, but the second start will make the app busy and ANR at `new JSContext()`.

JS code:

    for (var i = 0; i < 10000; i++) {
        func(i)
    }

Java code in TestActivity.onCreate:

    mJsContext = new JSContext();
    mJsContext.property("func", new JSFunction(mJsContext, "func") {
        public void func(int i) {
        }
    });

    long start = System.currentTimeMillis();
    mJsContext.evaluateScript(js);
    long end = System.currentTimeMillis();
    long time = end - start;

**Comment by ericwlange** [comment]
The issue is that every one of those calls is coming through JNI, which is [notoriously slow](http://stackoverflow.com/questions/7699020/what-makes-jni-calls-slow).  For heavy transactions, you want to avoid calling back to Java too much.  Is it possible to implement the code such that all of the work is done on the JavaScript side with limited callbacks?

I have been trying to think about how to speed interactions between Java & JavaScript.  My plan is to extend `JSArrayBuffer` so that you can share memory in an `ArrayBuffer` in JavaScript with a `ByteBuffer` in Java.  That way they are both accessing the same physical memory so you can communicate efficiently between them.  You would then just define some sort of protocol between them.  I haven't quite figured out how to handle concurrency yet.  There would need to be some sort of shared mutex lock as well.

You can see [my plans for 3.1.0](https://github.com/ericwlange/AndroidJSCore/wiki).  I have been planning to add this kind of support.  In the meantime, you should optimise away from having Java called 50k times from JavaScript.  Limit the JNI interactions and it should be plenty fast.

**Comment by LiuHongtao** [comment]
Thanks you so much.

The code upon is a Test work and 50k times call may not happen in actual development. As you say, I plan to move some work on JavaScript side to decrease number of times.

One more little question, at the last part of OwenMatthewsExample:

    Thing thing = new Thing(context);                
    thing.name.set("Alfred");                        
    thing.number.set(3);                             
    context.property("thing",thing);                 
    JSValue thingValue = context.property("thing");  
    context.log("Thing: " + thing);                  
    context.log("Thing JSValue: " + thingValue);     
    
    thing.name.set("Betty");                         
    thing.number.set(8);                             
    context.log("Thing: " + thing);                  
    context.log("Thing JSValue: " + thingValue);     
    
    context.evaluateScript(                          
        "thing.name = \"Carlos\"; thing.number = 5");
    context.log("Thing: " + thing);                  
    context.log("Thing JSValue: " + thingValue);     

The last log print shows the Number is 8, not 5. Does that mean values can't be set like "thing.number = 5" and get in Java side?

**Comment by ericwlange** [comment]
That example is just showing a case where `number` is private, but `name` is public.  In that case, javascript can modify public values but not private ones.  It's actually not a very useful example.  I was just copying what Owen had done verbatim.
